### ISSUE TITLE
Feature Idea: param type "positionalMany"

### ISSUE THREAD

**Issue by GreenRaccoon23** [provejs/provejs-handlebars#1]
# Feature Idea

Allow a param to have a `type` of `positionalMany`.

## Problem 1

Say a helper allows any number of params. For example:

```handlebars
{{#ifAny case1 case2 case3}}{{/ifAny}}
```

Currently, the config must have a separate rule for each param. Since this helper does not have a set number of params, the config could not have a rule for each one, so it could not cover all of them.

## Solution 1

I think it would be possible to support this situation by creating a new type called `positionalMany`. *(There might be a better name for it.)* The config would look like this:

```javascript
var config = {
	helpers: {
		ifAny: {
			params: [{
				name: 'cases',
				type: 'positionalMany',
				formats: ['variable'],
				position: 0,
				required: true
			}]
		}
	}
};
```

By making it a separate type, it could have its own validation process/function which looks at multiple params instead of just one.

## Problem 2

Also, say a helper has a set number of `positional` params followed by any number of `positionalMany` ones. For example:

```handlebars
{{#isAny var1 case1 case2 case3}}{{/isAny}}
```

The config for `var1` might need to be different than the config for `case1`, `case2`, and `case3`.

## Solution 2

In this case, the config could look like this:

```javascript
var config = {
	helpers: {
		isAny: {
			params: [{
				name: 'var1',
				type: 'positional',
				formats: ['variable'],
				position: 0,
				required: true
			}, {
				name: 'cases',
				type: 'positionalMany',
				formats: ['string', 'number'],
				position: 1,
				required: true
			}]
		}
	}
};
```

In this example config, the `'positionalMany'` rule would apply to all params starting at `position`, so all but the first param.

Since `required` is true, there must be at least one of them, so there must be a param at `position`. If `required` were false, there would not need to be a param at `position`.

## Additional Notes

There might be a better name than `positionalMany`. Maybe `positionalAny`? Maybe `...positional` or `positionalRest` *(like [the rest operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters))*?

Also, would there be a situation where more than 1 parameter in a `positionalMany` set is required? For example, requiring at least 2 parameters. I cannot imagine a situation like this, but it may come up. If so, there could be an `atleast` setting, or the `required` setting could take a number.

**Comment by dhollenbeck** [comment]
Perhaps, we should move the param rule configuration closer to how provejs-jquery works. I propose:

- name (**string**): required name of parameter. Used in the linter error messages.
- selector (**string**| **number**|**function**): required selector which borrows ideas from jQuery selector syntax.
- formats (**array**|**function**): optional param value types. If formats is undefined then any param is accepted.
- required (**number**): required indicator of if the number of params that are required.
- message (**string**): custom linter message.

The param selector would accept the following:
- '*' : all parameters including both positional and named parameters
- '#paramName' : a named parameter
- 'eq(nth)': positional nth parameter
- 'gt(nth)' : greater than nth parameter

## Example 1
```hbs
{{#ifAny case1 case2 case3}}{{/ifAny}}
```
There needs to be one or more case positional parameter
```js
params: {
  cases: {
    selector: 'eq(*)',
    required: 1
  }
}
```
## Example 2
```hbs
{{#isAny var1 case1 case2 case3}}{{/isAny}}
```
```js
params: {
  var1: {
    selector: 'eq(0)',
    required: 1
  },
  cases: {
    selector: 'gt(0)',
    required: 1
  }
}
```

## Example 3
```hbs
{{nest template='subtemplate'}}
```
```js
params: {
  template: {
    selector: '#template',
    formats: ['string'],
    required: 1
  }
}
```

## Example 4
```hbs
{{#if condition}}{{/if}}
```
```js
params: {
  condition: {
    selector: 'eq(0)',
    required: 1
  }
}
```

This design is much better. However, I still want to validate/lint a custom helper like:

## Example 5
```hbs
{{#if a1 'OR' b1 'OR' c1}}{{/if}}
{{#if a1 '=' a2 'OR' b1 '=' b2 'OR' c1 = c2}}{{/if}}
```
```js
params: function(positionalParams, namedParameters, helperLocation) {
  // todo: parse the array of parameters here
  // on errror or warning return something like below.
  // the start and end data will be found in the positionalParms and namedParams values
  // however you also have the overall helper location to use as well. 
  return {
    severity: 'error',
    message: '...',
    start: { line: 0, column: 0},
    end: {line: 0, column: 20}
  }
}
 
```

**Comment by GreenRaccoon23** [comment]
I think that idea is better. Using jQuery selectors would make adding more features easy.

What about allowing `required` to be either a number or a bool? It might seem a little odd to put `required: 1` for named params.

Also, which of these 2 is better?

## Example 1

```javascript
params: function(positionalParams, namedParameters, helperLocation) {
	// ...
}
```

## Example 2

```javascript
params: {
	all: function(positionalParams, namedParameters, helperLocation) {
		// ...
	}
}
```

The second example would allow multiple custom functions or a set of rules plus a custom function. I am guessing that this would be useful because then you could have a list of shared "prove helpers" which you drop into the config. Like this:

## Example 3

```javascript
params: {
	allNamed: proveHelper1,
	allPositional: proveHelper2
}
```

Or maybe you could register validators like handlebars does with `Handlebars.registerHelper()`. This is starting to become a separate issue, but it is somewhat related. I am imagining this:

## Example 4

```javascript
var Handlebars = require('handlebars');
var Prove = require('provejs-handlebars');
var Validators = require('./validators');

Prove.registerValidators(Validators);

var config = {
	helpers: {
		myHelper: {
			params: {
				allNamed: Prove.validator1, // or `Validators.validator1`
				allPositional: Prove.validator2 // or `Validators.validator2`
			}
		}
	}
};
var html = '{{helper1 foobar='goo'}}\n{{helper2 'zoo' 'goo'}}';
var ast = Handlebars.parse(html);
var errors = Prove(config, ast);
```

**Comment by dhollenbeck** [comment]
Thanks for the feedback!

**Required**: now supports bool and integers.

**Custom Validators**: I like your suggestion of a more granular custom validator. The primary use-case I see is to warn or error on extra parameters passed into the helpers.  Passing in extra params can cause isssues for poorly written helpers and in the case of the built-in {{if}} helper Handlebars will throw an error with more than a single param. Therefore, you can use a custom function to always return an error for extra params. However, I might consider coding a solution for this, which can be turned on or off.

Thanks much!
